import { describe, expect, it } from 'vitest';
import type {
  ArtifactsConfig,
  CanonicalObservabilityMetric,
  DiagnosisEvidence,
  DiagnosisSuspect,
  EvidenceBundle,
  ExecuteOptions,
  ExecutionDescriptorCore,
  ExecutionError,
  ExecutionErrorCode,
  ExecutionMeta,
  ExecutionMetadata,
  ExecutionRequest,
  ExecutionResponse,
  ExecutionResult,
  ExecutionStats,
  ExecutionTarget,
  HealthStatus,
  IExecutionBackend,
  IPlatformGateway,
  ISubprocessRunner,
  ObservabilityCapability,
  ObservabilityCheck,
  RunResult,
  ServiceDependencyDescriptor,
  ServiceHealthStatus,
  ServiceObservabilityDescribe,
  ServiceObservabilityHealth,
  ServiceObservabilityState,
  ServiceOperationSample,
  ResourceSnapshot,
  WorkspaceConfig,
} from '../index.js';

const REQUIRED_EXPORTS = [
  'ExecutionRequest',
  'ExecutionResponse',
  'ExecutionResult',
  'ExecutionError',
  'ExecutionErrorCode',
  'ExecutionMetadata',
  'ExecuteOptions',
  'ExecutionDescriptorCore',
  'ExecutionTarget',
  'WorkspaceConfig',
  'ArtifactsConfig',
  'CANONICAL_OBSERVABILITY_METRICS',
  'checkCanonicalObservabilityMetrics',
  'ExecutionMeta',
  'RunResult',
  'IExecutionBackend',
  'HealthStatus',
  'ExecutionStats',
  'IPlatformGateway',
  'ISubprocessRunner',
  'OBSERVABILITY_CAPABILITIES',
  'OBSERVABILITY_CONTRACT_VERSION',
  'OBSERVABILITY_SCHEMA',
  'validateServiceObservabilityDescribe',
  'validateServiceObservabilityHealth',
] as const;

type _CompileTimeContractPresence = [
  ArtifactsConfig,
  CanonicalObservabilityMetric,
  DiagnosisEvidence,
  DiagnosisSuspect,
  EvidenceBundle,
  ExecuteOptions,
  ExecutionDescriptorCore,
  ExecutionError,
  ExecutionErrorCode,
  ExecutionMeta,
  ExecutionMetadata,
  ExecutionRequest,
  ExecutionResponse,
  ExecutionResult,
  ExecutionStats,
  ExecutionTarget,
  HealthStatus,
  IExecutionBackend,
  IPlatformGateway,
  ISubprocessRunner,
  ObservabilityCapability,
  ObservabilityCheck,
  ResourceSnapshot,
  RunResult,
  ServiceDependencyDescriptor,
  ServiceHealthStatus,
  ServiceObservabilityDescribe,
  ServiceObservabilityHealth,
  ServiceObservabilityState,
  ServiceOperationSample,
  WorkspaceConfig,
];

describe('core-contracts entrypoint contract', () => {
  it('exports required canonical contracts', () => {
    expect(REQUIRED_EXPORTS.length).toBeGreaterThan(0);
  });
});
