/**
 * Analytics event types for Core CLI
 * Centralized constants to prevent typos and enable type safety
 */

/**
 * Event type prefixes by command
 */
export const ANALYTICS_PREFIX = {
  // Bundle commands
  BUNDLE_PRINT: 'core.bundle.print',
  BUNDLE_INSPECT: 'core.bundle.inspect',
  // Config commands
  CONFIG_GET: 'core.config.get',
  CONFIG_INSPECT: 'core.config.inspect',
  CONFIG_VALIDATE: 'core.config.validate',
  CONFIG_EXPLAIN: 'core.config.explain',
  CONFIG_DOCTOR: 'core.config.doctor',
  // Init commands
  INIT_WORKSPACE: 'core.init.workspace',
  INIT_PROFILE: 'core.init.profile',
  INIT_POLICY: 'core.init.policy',
  INIT_SETUP: 'core.init.setup',
  // Profiles commands
  PROFILES_RESOLVE: 'core.profiles.resolve',
  PROFILES_VALIDATE: 'core.profiles.validate',
  PROFILES_INSPECT: 'core.profiles.inspect',
} as const;

/**
 * Event lifecycle suffixes
 */
export const ANALYTICS_SUFFIX = {
  STARTED: 'started',
  FINISHED: 'finished',
} as const;

/**
 * Core analytics event types
 */
export const ANALYTICS_EVENTS = {
  // Bundle events
  BUNDLE_PRINT_STARTED: `${ANALYTICS_PREFIX.BUNDLE_PRINT}.${ANALYTICS_SUFFIX.STARTED}`,
  BUNDLE_PRINT_FINISHED: `${ANALYTICS_PREFIX.BUNDLE_PRINT}.${ANALYTICS_SUFFIX.FINISHED}`,
  BUNDLE_INSPECT_STARTED: `${ANALYTICS_PREFIX.BUNDLE_INSPECT}.${ANALYTICS_SUFFIX.STARTED}`,
  BUNDLE_INSPECT_FINISHED: `${ANALYTICS_PREFIX.BUNDLE_INSPECT}.${ANALYTICS_SUFFIX.FINISHED}`,

  // Config events
  CONFIG_GET_STARTED: `${ANALYTICS_PREFIX.CONFIG_GET}.${ANALYTICS_SUFFIX.STARTED}`,
  CONFIG_GET_FINISHED: `${ANALYTICS_PREFIX.CONFIG_GET}.${ANALYTICS_SUFFIX.FINISHED}`,
  CONFIG_INSPECT_STARTED: `${ANALYTICS_PREFIX.CONFIG_INSPECT}.${ANALYTICS_SUFFIX.STARTED}`,
  CONFIG_INSPECT_FINISHED: `${ANALYTICS_PREFIX.CONFIG_INSPECT}.${ANALYTICS_SUFFIX.FINISHED}`,
  CONFIG_VALIDATE_STARTED: `${ANALYTICS_PREFIX.CONFIG_VALIDATE}.${ANALYTICS_SUFFIX.STARTED}`,
  CONFIG_VALIDATE_FINISHED: `${ANALYTICS_PREFIX.CONFIG_VALIDATE}.${ANALYTICS_SUFFIX.FINISHED}`,
  CONFIG_EXPLAIN_STARTED: `${ANALYTICS_PREFIX.CONFIG_EXPLAIN}.${ANALYTICS_SUFFIX.STARTED}`,
  CONFIG_EXPLAIN_FINISHED: `${ANALYTICS_PREFIX.CONFIG_EXPLAIN}.${ANALYTICS_SUFFIX.FINISHED}`,
  CONFIG_DOCTOR_STARTED: `${ANALYTICS_PREFIX.CONFIG_DOCTOR}.${ANALYTICS_SUFFIX.STARTED}`,
  CONFIG_DOCTOR_FINISHED: `${ANALYTICS_PREFIX.CONFIG_DOCTOR}.${ANALYTICS_SUFFIX.FINISHED}`,

  // Init events
  INIT_WORKSPACE_STARTED: `${ANALYTICS_PREFIX.INIT_WORKSPACE}.${ANALYTICS_SUFFIX.STARTED}`,
  INIT_WORKSPACE_FINISHED: `${ANALYTICS_PREFIX.INIT_WORKSPACE}.${ANALYTICS_SUFFIX.FINISHED}`,
  INIT_PROFILE_STARTED: `${ANALYTICS_PREFIX.INIT_PROFILE}.${ANALYTICS_SUFFIX.STARTED}`,
  INIT_PROFILE_FINISHED: `${ANALYTICS_PREFIX.INIT_PROFILE}.${ANALYTICS_SUFFIX.FINISHED}`,
  INIT_POLICY_STARTED: `${ANALYTICS_PREFIX.INIT_POLICY}.${ANALYTICS_SUFFIX.STARTED}`,
  INIT_POLICY_FINISHED: `${ANALYTICS_PREFIX.INIT_POLICY}.${ANALYTICS_SUFFIX.FINISHED}`,
  INIT_SETUP_STARTED: `${ANALYTICS_PREFIX.INIT_SETUP}.${ANALYTICS_SUFFIX.STARTED}`,
  INIT_SETUP_FINISHED: `${ANALYTICS_PREFIX.INIT_SETUP}.${ANALYTICS_SUFFIX.FINISHED}`,

  // Profiles events
  PROFILES_RESOLVE_STARTED: `${ANALYTICS_PREFIX.PROFILES_RESOLVE}.${ANALYTICS_SUFFIX.STARTED}`,
  PROFILES_RESOLVE_FINISHED: `${ANALYTICS_PREFIX.PROFILES_RESOLVE}.${ANALYTICS_SUFFIX.FINISHED}`,
  PROFILES_VALIDATE_STARTED: `${ANALYTICS_PREFIX.PROFILES_VALIDATE}.${ANALYTICS_SUFFIX.STARTED}`,
  PROFILES_VALIDATE_FINISHED: `${ANALYTICS_PREFIX.PROFILES_VALIDATE}.${ANALYTICS_SUFFIX.FINISHED}`,
  PROFILES_INSPECT_STARTED: `${ANALYTICS_PREFIX.PROFILES_INSPECT}.${ANALYTICS_SUFFIX.STARTED}`,
  PROFILES_INSPECT_FINISHED: `${ANALYTICS_PREFIX.PROFILES_INSPECT}.${ANALYTICS_SUFFIX.FINISHED}`,
} as const;

/**
 * Type helper for analytics event types
 */
export type AnalyticsEventType = typeof ANALYTICS_EVENTS[keyof typeof ANALYTICS_EVENTS];

/**
 * Actor configuration for Core analytics
 */
export const ANALYTICS_ACTOR = {
  type: 'agent' as const,
  id: 'core-cli',
} as const;

