schemaVersion: "1.0"
$extends: "@kb-labs/org-preset@^1.0.0"
profiles:
  default: "node-ts-lib@1.2.0"
  production: "node-ts-lib@1.2.0"
  testing: "node-ts-lib@1.2.0"
products:
  ai-review:
    rules:
      - "custom-rules.yml"
    maxFiles: 50
    debug: true
  release:
    version: "1.0.0"
    prerelease: false
policy:
  overrides:
    roles:
      developer:
        - "aiReview.run"
        - "devkit.sync"
      maintainer:
        - "release.publish"
        - "profiles.materialize"
