name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  drift-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js and pnpm
        uses: KirillBaranov/kb-labs-devkit/.github/actions/setup-node-pnpm@main
        with:
          node-version: '20'
          pnpm-version: '9.x'
      
      - name: Install dependencies
        run: pnpm i
      
      - name: Check sync drift
        run: pnpm sync:check

  ci:
    needs: drift-check
    uses: KirillBaranov/kb-labs-devkit/.github/workflows/ci.yml@main
    with:
      node-version: '20'
      run-coverage: true